{% set name = "prismatique" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prismatique-{{ version }}.tar.gz
  sha256: c15d1a77a5e8764bb0d5a65c25c797e564f7d1ba6b42d32b8cfa58c9178cfefb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - embeam >=0.0.5
    - h5pywrappers
    - pyprismatic >=2.0

test:
  imports:
    - prismatique
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/prismatique/
  summary: A wrapper to the Python library `pyprismatic`, which is a library for simulating CBED, STEM, and HRTEM experiments using Multislice algorithms.
  dev_url: https://github.com/mrfitzpa/prismatique
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
